### ISSUE TITLE
Error when posting picture

### ISSUE THREAD

**Issue by gronnmann** [austinv11/Discord4J#270]
### Prerequisites
* [ ] If this is a question/suggestion, I have already considered talking about it on the [Discord4J server](https://discord.gg/NxGAeCY)
* [ ] This issue specifically has something to do with Discord4J
* [ ] I have attempted to [look for similar issues](https://github.com/austinv11/Discord4J/issues?utf8=%E2%9C%93&q=is%3Aissue) already

### Description
Throws error when I try to post picture.
Whole code:
if (msg.startsWith("!meme")){
			
			String[] args = msg.split(" ");
			
			int count = 1;
			
			if (args.length != 0){
				try{
					int countN = Integer.parseInt(args[1]);
					count = countN;
					
					if (count > 100){
						count = 100;
					}
				}catch(Exception ex){}
			}
			
			
			SubredditPaginator pag = new SubredditPaginator(BobmakerBot.getReddit());
			
			pag.setLimit(100);
			pag.setSorting(Sorting.TOP);
			pag.setTimePeriod(TimePeriod.DAY);
			pag.setSubreddit("dankmemes");
			pag.next(true);
			
			Listing<Submission> submissions = pag.getCurrentListing();
			
			for (int i = 0; i < count; i++){
				Random r = new Random();
				
				Submission meme = submissions.get(r.nextInt(submissions.size()));
				
				MessageUtils.log("Meme: '" + meme.getUrl() + "' by '" + meme.getAuthor() + "'.");
				
				//e.getChannel().sendMessage(meme.getUrl());
				
				String fileN = meme.getUrl().split("/")[3];
				
				MessageUtils.log(fileN);
				 	
				
				try {
					BufferedImage img = ImageIO.read(new URL(meme.getUrl()));
					File temp = File.createTempFile("meme", ".jpg");
					
					ImageIO.write(img, "jpg", temp);
					
					e.getChannel().sendFile(temp);
					
					if (count > 1){
						wait(1000);
					}
					
				} catch (Exception e1) {
				}
			
			}
			
			e.getChannel().sendMessage("Posted " + count + " dank meme(s). Enjoy!");
					
		}
		
	}
### Steps to Reproduce
1. [First step]
2. [Second step]

...

**Expected behavior:** Posts picture

**Actual behavior:** No picture, post deleted as specified by event, but throws stacktrace. 

**Stacktrace (if applicable):** 
15:41:00.583: [WARN][RequestBuffer Initial Executor][sx.blah.discord.Discord4J] - RequestBuffer handled an uncaught exception!
java.lang.NullPointerException
	at sx.blah.discord.api.internal.DiscordUtils.getMessageFromJSON(DiscordUtils.java:424)
	at sx.blah.discord.handle.impl.obj.Channel.lambda$null$18(Channel.java:562)
	at sx.blah.discord.util.RequestBuffer$RequestFuture$RequestCallable.call(RequestBuffer.java:289)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at sx.blah.discord.util.RequestBuffer$RequestFuture.run(RequestBuffer.java:264)
	at sx.blah.discord.util.RequestBuffer$RequestFuture.access$200(RequestBuffer.java:165)
	at sx.blah.discord.util.RequestBuffer.lambda$request$0(RequestBuffer.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Version affected:** [The version of Discord4J]dev-SNAPSHOT

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by FerusGrim** [comment]
1. You really went all out, properly filling in the information they ask for, didn't you?
    1. http://i.imgur.com/DojTFew.png
    2. http://i.imgur.com/yNGa5e5.png
    3. http://i.imgur.com/5Gv0a0n.png
2. `if (args.length != 0)` is _always_ true.
3. You should `split("\\s+")` instead of `split(" ")`
4. You should do that split before checking what the message starts with, otherwise `!memelol` would also trigger. That's probably unexpected behavior.
5. I'm going to assume that `e` is the event because, regardless of your prefacing, this isn't the whole code and I have no idea what you've named the event object or what may have come before the message check.
6. This isn't an issue with Discord4J. This is a problem with your code. Git Issues is not the place to take your programming questions.
7. For problems with your code, I suggest you join the D4J Discord server and ask for help in #programming-help or #api-help, in the future.
8. In the future, letting us know, exactly, which line the error occurs on would be helpful.
9. I'm going to - again, have to - assume that the NPE is being thrown at the end, because the only other `sendMessage()` line is commented out.
10. Assuming that, I can't fathom what the problem is. Unless `count == null` somehow. But even then, it shouldn't throw an NPE.
11. Keeping that in mind, I'm going to assume the commented-out line is _actually_ the problem and you've, for some reason, modified the code before asking for help.
12. In which case it becomes pretty obvious that your issue is `meme == null`. Again, a problem with your code.
13. Have a nice day.

**Comment by theIglooo** [comment]
Could you try reimporting Discord4J? I'm pretty sure this was fixed on [this commit](https://github.com/austinv11/Discord4J/commit/e0ad78e527d7e07f9a624f90825ebf96a8a203d3). The line in your stacktrace points to `return null;` in the current dev code.

Also in the future, we log the actual commit hash when you first start up the bot. Please provide that instead of dev-SNAPSHOT because snapshots vary greatly depending on when you import your dependencies.

**Comment by gronnmann** [comment]
Running version Discord4J v2.7.1-SNAPSHOT (dev-26e98a9) (newest when I maven install), still doesnt work. The bot also for some reasons deletes every message I type and throws the same error. The code I used worked yesterday though, so its weird it doesnt today.

**Comment by decyg** [comment]
I'm afraid that's still not the latest version, use the version 2.8.0 instead, there's been a slew of fixes since dev, the issues are most likely your code as the d4j example bot linked on the wiki works perfectly on 2.8.0

**Comment by gronnmann** [comment]
Thanks, changing version to 2.8.0 worked :)

**Comment by decyg** [comment]
Glad it worked :)
